### PR TITLE
add: ability to show all encoding problems at once

### PR DESCRIPTION
**Pull request by sharikovvladislav**
The problem: now, the tool finds the first error and fails immediately. If there are many files to check more then once file can have bad encoding.

Solution: add the ability to show all problems at once.

Example: in snapshots directory.

Also added tests.

Also:
- I recommend you to bump major version because somebody who use this package perhaps doesn't expect this
- I recommend you to add CI (circleci, travis and stuff) and run tests there

### CODE REVIEW

**Comment by sharikovvladislav** [comment]
@akaguny @XFree FYI. Any comments on this?

**Comment by akaguny** [comment]
@sharikovvladislav , no. If you whant tell advice you mast create issue. It`s good way)

**Comment by sharikovvladislav** [comment]
@akaguny I am not sure that adding unnecessary entities is okay. PR is enough. I think we can discuss stuff both in PRs and issues.

**Comment by akaguny** [comment]
@sharikovvladislav , if you discuss in PR focus is blur... If entitie realy unnecessary he will be closed

**Pull request merged**
